import Car from "./Car";
import Colors from "./Colors";
import Doors from "./Doors";
import Directions from "./Directions";

const car = new Car("Volkswagen", Colors.Silver, 4);

car.openTheDoor(Doors.FrontLeft);
car.closeTheDoor(Doors.FrontLeft);
car.turnOn();
car.speedUp();
car.speedDown();
car.turn(Directions.Left);
car.speedUp();
car.speedDown();
car.turn(Directions.Right);
car.speedUp();
car.speedDown();
car.turn(Directions.Right);
car.speedUp();
car.speedDown();
car.stop();
car.openTheDoor(Doors.BackRight);
car.closeTheDoor(Doors.BackRight);
car.speedUp();
car.speedDown();
car.turn(Directions.Right);
car.speedUp();
car.speedDown();
car.turn(Directions.Left);
car.speedUp();
car.speedDown();
car.turn(Directions.Right);
car.speedUp();
car.speedDown();
car.stop();
car.openTheDoor(Doors.BackRight);
car.closeTheDoor(Doors.BackRight);
car.turnOff();
