# Crie um Dockerfile utilizando a imagem chuanwen/cowsay
FROM chuanwen/cowsay:latest

# Defina um ENTRYPOINT para a execução do comando
ENTRYPOINT [ "/usr/games/cowsay" ]

# Utilize o CMD para definir uma mensagem padrão
CMD [ "Muuuuuuhhh" ]

# Builde e execute um container baseado em sua imagem sem passar nenhum comando
# docker image build ./ -t cowsay

# docker container run cowsay -f moofasa "#VQV TRYBE"